[package]
name = "macros"
version = "0.1.0-dev"
edition = "2018"
authors = ["Jonas Jebing <noreply.jonas.8049@protonmail.com>"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
macros_impl = { path = "../macros_impl" }
syn = "1.0"
